# Generated by Django 5.1.2 on 2025-11-20 08:43

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to=catalog.models.book_cover_upload),
        ),
    ]
