# Generated by Django 5.1.2 on 2025-12-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shelf_number',
            field=models.CharField(blank=True, help_text='Shelf location in the store', max_length=50),
        ),
    ]
